version: '3.8'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3384:3306
    environment:
      MYSQL_DATABASE: recipe_db
      MYSQL_USER: recipe_db
      MYSQL_PASSWORD: '9C4et0*xU7U4'
      MYSQL_RANDOM_ROOT_PASSWORD: '60w!F9Wt5zvy'
    volumes:
      - 'db:/var/lib/mysql'

volumes:
  db: